default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # A list of supported hooks can be found here: https://pre-commit.com/hooks.html.
    rev: v4.6.0
    hooks:
    - id: mixed-line-ending
      args: [ '--fix=lf' ]
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-toml
    - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      # Run the linter
      - id: ruff
        args: [ --fix ]
      # Run the formatter
      - id: ruff-format
